@startuml

' Old Architecture
class Car {
    - final String _id
    - final String _model
    - final String _brand
    + Car(id: String, model: String, brand: String)
    + getId(): String
    + getModel(): String
    + getBrand(): String
}

class CarManager {
    + getFromDb(carId: String): Car
    + getCarsNames(): String
    + getBestCar(): Car
}

CarManager --> " *" Car 

@enduml
